services:
  - type: web
    name: operation-acier
    env: node
    plan: free
    nodeVersion: 20
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false